import { db } from './db';
import { v4 as uuidv4 } from 'uuid';
import { format, addDays } from 'date-fns';
import type { Subscription, HouseholdMember, AlertTiming } from '@/types';

function d(daysFromNow: number): string {
  return format(addDays(new Date(), daysFromNow), 'yyyy-MM-dd');
}

const now = new Date().toISOString();

export async function loadDemoData() {
  // Clear existing data
  await db.subscriptions.clear();
  await db.householdMembers.clear();

  // Get category IDs by name
  const categories = await db.categories.toArray();
  const cat = (name: string) => categories.find((c) => c.name === name)?.id ?? categories[0].id;

  // Household members
  const members: HouseholdMember[] = [
    { id: uuidv4(), name: 'Alex', role: 'admin', avatarColor: '#3B82F6', createdAt: now },
    { id: uuidv4(), name: 'Jordan', role: 'member', avatarColor: '#EC4899', createdAt: now },
    { id: uuidv4(), name: 'Sam', role: 'member', avatarColor: '#22C55E', createdAt: now },
  ];
  await db.householdMembers.bulkAdd(members);

  const [alex, jordan, sam] = members;

  const base = {
    currency: 'USD',
    hasIntroPricing: false,
    renewalDayRule: 'exact' as const,
    autoRenew: true,
    cancellationNeeded: false,
    alertDaysBefore: [7, 3, 1] as AlertTiming[],
    isShared: false,
    addOns: [],
    priceHistory: [],
    tags: [],
    createdAt: now,
    updatedAt: now,
  };

  const subs: Subscription[] = [
    {
      ...base,
      id: uuidv4(),
      name: 'Netflix',
      categoryId: cat('Streaming'),
      billingCycle: 'monthly',
      amount: 22.99,
      startDate: '2023-03-15',
      nextRenewalDate: d(5),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id, jordan.id, sam.id],
      isShared: true,
      lastUsed: 'within7',
      valueScore: 5,
      wouldMiss: true,
      tags: ['entertainment', 'family'],
      priceHistory: [
        { date: '2023-03-15', amount: 15.49 },
        { date: '2024-01-01', amount: 22.99, note: 'Premium plan increase' },
      ],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Spotify Family',
      categoryId: cat('Music'),
      billingCycle: 'monthly',
      amount: 16.99,
      startDate: '2022-08-01',
      nextRenewalDate: d(12),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id, jordan.id, sam.id],
      isShared: true,
      seatCount: 6,
      lastUsed: 'within7',
      valueScore: 5,
      wouldMiss: true,
      tags: ['music', 'family'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'iCloud+',
      categoryId: cat('Cloud Storage'),
      billingCycle: 'monthly',
      amount: 2.99,
      startDate: '2021-11-20',
      nextRenewalDate: d(18),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id],
      lastUsed: 'within7',
      valueScore: 4,
      wouldMiss: true,
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Adobe Creative Cloud',
      categoryId: cat('Software'),
      billingCycle: 'annual',
      amount: 659.88,
      startDate: '2024-06-01',
      nextRenewalDate: d(45),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id],
      lastUsed: 'within30',
      valueScore: 3,
      wouldMiss: false,
      cancelMethod: 'website',
      cancelUrl: 'https://account.adobe.com',
      tags: ['work', 'design'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Disney+',
      categoryId: cat('Streaming'),
      billingCycle: 'annual',
      amount: 139.99,
      startDate: '2024-09-10',
      nextRenewalDate: d(22),
      status: 'active',
      payerId: jordan.id,
      ownerId: jordan.id,
      userIds: [alex.id, jordan.id, sam.id],
      isShared: true,
      lastUsed: 'within30',
      valueScore: 3,
      wouldMiss: true,
      tags: ['entertainment', 'family'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'ChatGPT Plus',
      categoryId: cat('Software'),
      billingCycle: 'monthly',
      amount: 20.00,
      startDate: '2024-02-14',
      nextRenewalDate: d(3),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id],
      lastUsed: 'within7',
      valueScore: 5,
      wouldMiss: true,
      tags: ['ai', 'work'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'YouTube Premium',
      categoryId: cat('Streaming'),
      billingCycle: 'monthly',
      amount: 13.99,
      startDate: '2023-07-22',
      nextRenewalDate: d(8),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id, jordan.id],
      isShared: true,
      lastUsed: 'within7',
      valueScore: 4,
      wouldMiss: true,
      tags: ['entertainment'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Gym Membership',
      categoryId: cat('Fitness'),
      billingCycle: 'monthly',
      amount: 49.99,
      startDate: '2024-01-02',
      nextRenewalDate: d(15),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id],
      lastUsed: 'over90',
      valueScore: 1,
      wouldMiss: false,
      cancelMethod: 'phone',
      cancelDeadlineDays: 30,
      notes: 'Need to call to cancel, 30-day notice required',
      tags: ['health'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'NordVPN',
      categoryId: cat('Security'),
      billingCycle: 'biannual',
      amount: 89.99,
      startDate: '2024-04-15',
      nextRenewalDate: d(60),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id, jordan.id],
      isShared: true,
      seatCount: 6,
      lastUsed: 'within30',
      valueScore: 4,
      wouldMiss: true,
      tags: ['privacy'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'New York Times',
      categoryId: cat('News & Reading'),
      billingCycle: 'monthly',
      amount: 17.00,
      startDate: '2023-11-01',
      nextRenewalDate: d(10),
      status: 'active',
      payerId: jordan.id,
      ownerId: jordan.id,
      userIds: [alex.id, jordan.id],
      isShared: true,
      lastUsed: 'within7',
      valueScore: 4,
      wouldMiss: true,
      tags: ['news'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Xbox Game Pass',
      categoryId: cat('Gaming'),
      billingCycle: 'monthly',
      amount: 19.99,
      startDate: '2024-05-10',
      nextRenewalDate: d(2),
      status: 'active',
      payerId: sam.id,
      ownerId: sam.id,
      userIds: [sam.id],
      lastUsed: 'within7',
      valueScore: 5,
      wouldMiss: true,
      tags: ['gaming'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Paramount+',
      categoryId: cat('Streaming'),
      billingCycle: 'monthly',
      amount: 11.99,
      hasIntroPricing: true,
      introPrice: 5.99,
      introDurationDays: 30,
      introEndDate: d(-10),
      startDate: '2025-01-05',
      nextRenewalDate: d(20),
      status: 'trial',
      payerId: jordan.id,
      ownerId: jordan.id,
      userIds: [jordan.id],
      lastUsed: 'within30',
      valueScore: 2,
      wouldMiss: false,
      tags: ['entertainment'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Dropbox Plus',
      categoryId: cat('Cloud Storage'),
      billingCycle: 'annual',
      amount: 119.88,
      startDate: '2023-06-15',
      nextRenewalDate: d(28),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id],
      lastUsed: 'within90',
      valueScore: 2,
      wouldMiss: false,
      notes: 'Barely using this since switching to iCloud. Consider cancelling.',
      tags: ['storage'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Notion',
      categoryId: cat('Work & Productivity'),
      billingCycle: 'monthly',
      amount: 10.00,
      startDate: '2024-08-01',
      nextRenewalDate: d(6),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id],
      lastUsed: 'within7',
      valueScore: 5,
      wouldMiss: true,
      tags: ['work', 'productivity'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'Home Insurance',
      categoryId: cat('Home & Utilities'),
      billingCycle: 'annual',
      amount: 1440.00,
      startDate: '2024-03-01',
      nextRenewalDate: d(14),
      status: 'active',
      payerId: alex.id,
      ownerId: alex.id,
      userIds: [alex.id, jordan.id],
      isShared: true,
      lastUsed: 'within30',
      valueScore: 5,
      wouldMiss: true,
      cancelMethod: 'phone',
      priceHistory: [
        { date: '2023-03-01', amount: 1200.00 },
        { date: '2024-03-01', amount: 1440.00, note: 'Rate increase' },
      ],
      tags: ['essential'],
    },
    {
      ...base,
      id: uuidv4(),
      name: 'ABCmouse',
      categoryId: cat('Kids & Family'),
      billingCycle: 'monthly',
      amount: 12.99,
      startDate: '2024-09-01',
      nextRenewalDate: d(25),
      status: 'active',
      payerId: jordan.id,
      ownerId: jordan.id,
      userIds: [sam.id],
      lastUsed: 'never',
      valueScore: 1,
      wouldMiss: false,
      notes: 'Sam never uses this anymore. Cancel next month.',
      tags: ['kids', 'education'],
    },
  ];

  await db.subscriptions.bulkAdd(subs);

  return { subscriptions: subs.length, members: members.length };
}
